#coding: utf-8
"""
Django settings for opsweb project.

Generated by 'django-admin startproject' using Django 1.8.18.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'h4#bcbr)pjoqa49n5_f9-z2i5t5nfyj&wx0ahl!05&7j0l_9d!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'opsweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'opsweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'django_learn',
        'USER': 'sunfan',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': 3506,
    },
    'cmdb': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'flask_learn',
        'USER': 'sunfan',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': 3506,
    }

}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

#如果没登录或者认证过期，默认转到这个URL,这是在view.py设置的权限。
LOGIN_URL = '/login/'
#如果登陆没权限则跳转到这个界面
PERMISSION_NONE_URL = '/permission/none'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
#页面跳转的模版
TEMPLATE_JUMP = 'public/jump.html'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'loggers':{
        'opsweb':{
            'level': 'DEBUG',
            'handlers': ['console_handler', 'opsweb_file_handler'],
            # 'propagate': True,#向上一级别传递,一般不用这个功能
        },
        'django':{
            'level': 'DEBUG',
            'handlers': ['django_handler'],
        },
        'django.request':{
            'level': 'DEBUG',
            'handlers': ['django_request'],
        },
    },
    'handlers':{
        'console_handler':{
           'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'opsweb_file_handler':{
           'class': 'logging.FileHandler',
           'filename': os.path.join(BASE_DIR, 'logs', 'opsweb.log'),
           'formatter': 'opsweb'
        },
        'django_handler':{
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'opsweb'
        },
        'django_request':{
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'request.log'),
            'formatter': 'opsweb'
        },
    },
    'formatters': {
		'opsweb':{
            'format': '%(asctime)s - %(pathname)s:%(lineno)d[%(levelname)s] - %(message)s'
        },
		'simple': {
			'format': '%(asctime)s %(levelname)s %(message)s'
		}
	},
    # 'root':{ #写法于opsweb一致，但是作用大不相同；它与logger级别相同，比opsweb高一级别，一般不用这个功能
    #         'level': 'DEBUG',
    #         'handlers': ['console_handler'],
    # },

}